version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: smsbot_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smsbot
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
    command: python -u bot/main.py
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  worker:
    build:
      context: .
    command: python -u worker/worker.py
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  web:
    build:
      context: .
    command: uvicorn web.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

volumes:
  db_data:
